CLASS LHC_ZR_TTGROCERY DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR Grocery
        RESULT result,
      checkExpirationDate FOR MODIFY
            keys FOR ACTION Grocery~checkExpirationDate RESULT result.
ENDCLASS.

CLASS LHC_ZR_TTGROCERY IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD checkExpirationDate.

  ENDMETHOD.

ENDCLASS.
